
title: Parcial 3 Machine Learning
author: Ricardo Watts
logo: logo.png

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex


repository:
  url: https://github.com/WaffleLovesCherries/Parcial3ML
  path_to_book: docs
  branch: main

html:
  use_issues_button: false
  use_repository_button: false
